- name: Actualizar el sistema
  apt: update_cache=yes upgrade=yes

- name: Copiar clave pública SSH
  authorized_key:
    user: usuario
    state: present
    key: "{{ lookup('file', '/home/arantxa/.ssh/id_rsa.pub') }}"

