- hosts: all
  become: true
  roles:
   - role: common

- hosts: router
  become: true
  roles:
   - role: router

- hosts: router
  become: true
  roles:
   - role: dhcp

- hosts: clientes       
  become: true
  roles:
   - role: cliente 

- hosts: cliente       
  become: true
  roles:
   - role: web 
